"""Load Train.csv into SQLite and run every named query in sql/queries.sql -> reports/sql_results.md"""
import re, sqlite3, sys
from pathlib import Path
import pandas as pd

data = Path(sys.argv[1] if len(sys.argv) > 1 else "data/raw/Train.csv")
con = sqlite3.connect(":memory:"); pd.read_csv(data).to_sql("sales", con, index=False)
text = Path("sql/queries.sql").read_text()
blocks = re.split(r"^-- name: (\w+)\n", text, flags=re.M)[1:]
out = ["# SQL analytics results\n", f"Source: `{data.name}` ({pd.read_sql('SELECT COUNT(*) n FROM sales', con).n[0]:,} rows). Generated by `scripts/sql_analytics.py`.\n"]
for name, body in zip(blocks[0::2], blocks[1::2]):
    comment = "\n".join(l[3:] for l in body.splitlines() if l.startswith("-- "))
    sql = "\n".join(l for l in body.splitlines() if not l.startswith("--")).strip()
    res = pd.read_sql(sql, con)
    out += [f"## {name}\n", f"{comment}\n", "```sql", sql, "```\n", "```text", res.to_string(index=False), "```\n"]
Path("reports/sql_results.md").write_text("\n".join(out)); print(f"ran {len(blocks)//2} queries -> reports/sql_results.md")
